package io.llambda.compiler.planner
import io.llambda

import llambda.compiler.{SourceLocated, ProcedureSignature}
import llambda.compiler.debug
import llambda.compiler.planner.{step => ps}

case class PlannedFunction(
  signature : ProcedureSignature,
  namedArguments : List[(String,  ps.TempValue)],
  steps : List[ps.Step],
  worldPtrOpt : Option[ps.WorldPtrValue],
  debugContextOpt : Option[debug.SubprogramContext]
) {
  /** Indicates if this procedure is internally generated by the compiler */
  val isArtificial = !debugContextOpt.isDefined
}
