package io.llambda.compiler.planner
import io.llambda

import llambda.compiler.ProcedureSignature
import llambda.compiler.debug
import llambda.compiler.planner.{step => ps}

case class PlannedFunction(
  signature: ProcedureSignature,
  namedArguments: List[(String,  ps.TempValue)],
  steps: List[ps.Step],
  debugContextOpt: Option[debug.SubprogramContext],
  irCommentOpt: Option[String] = None
) {
  /** Indicates if this procedure is internally generated by the compiler */
  val isArtificial = !debugContextOpt.isDefined
}
