from typegen.constants import BASE_TYPE

GENERATED_FILE_COMMENT = ("/*****************************************************************\n"
                          " * This file is generated by gen-types.py. Do not edit manually. *\n"
                          " *****************************************************************/\n"
                          "\n")

def type_name_to_clike_class(type_name):
    if type_name == BASE_TYPE:
        return "BoxedDatum"
    else:
        return type_name[0].upper() + type_name[1:] + "Value"

