package io.llambda.typegen

import java.io.File

package object writer {
  type OutputWriter = (ProcessedTypes) => Map[String, String]

  // Note this is a string to be included in generated C-like files. This file
  // isn't generated despite what the string says.
  val GeneratedClikeFileComment = "/************************************************************\n" + 
                                  " * This file is generated by typegen. Do not edit manually. *\n" +
                                  " ************************************************************/\n\n"
}
